### ISSUE TITLE
Torsion Sample

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulse#11]
As we have previously discussed, a torsion sample is needed. The sample will require further work to use DIC properly, but the first implementation will use just classical techniques.

Example data:
https://gist.github.com/bhalonen/64be952a0b6fd54ca52afa6ef5d915a0

Generated with:
https://gist.github.com/bhalonen/4080b945e4f6cf4edfcab4bba089cc8a

**Comment by markhalonen** [comment]
So I'm trying to figure out this thing... what I see in the notebook is a bunch of calculations that show what the expected voltage timeseries will be given some parameters of the shot... 

So my job is to take the voltage timeseries and produce... what? Stress-strain curves? How are those calculated?
