### ISSUE TITLE
Ragged Data Import

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulse#112]
> Will not import ragged data anymore but there is no warning or explanation.  I just fails to import

Waiting on data file

**Comment by markhalonen** [comment]
@jotaivalkoski can you try to track this down? Luke found a ragged file that doesn't give popup but he's keeping it a secret

An example would be 

```
time,voltage 1, voltage 2
1,3,4
2,3.1,4.1
3,2.3,5.6
,3.4,3.4
````

**Comment by markhalonen** [comment]
This is how I tried to fix it before: https://github.com/relinc/SurePulse/issues/82

So maybe just trying to build a unit test that fails is a good first step

**Comment by jotaivalkoski** [comment]
do we want to add an error function for ragged data?

**Comment by markhalonen** [comment]
it should show a dialog saying "Please fix your data" and not do anything else
