### ISSUE TITLE
Improve selected sample

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulse#113]
> Works partially.  Still can’t see with light colored samples.  Also, it doesn’t work in the current sample window.  I suggest the highlighted sample turns black and all others heavily fade or grey out.

**Comment by jotaivalkoski** [comment]
@markhalonen proposal: add Accordian TitlePane listeners so that the highlighted sample matches the selected sample(s) in the open title pane. I don't like black because you can select multiple samples.

**Comment by markhalonen** [comment]
> @markhalonen proposal: add Accordian TitlePane listeners so that the highlighted sample matches the selected sample(s) in the open title pane. I don't like black because you can select multiple samples.

I think our conclusion on this was to stay with black since you typically only select one Sample to trim?

**Comment by jotaivalkoski** [comment]
ChartsGUI.setSeriesColor(Series<Number, Number> series, String hexString) doesnt seem to work properly. It does not return a hex string equivalent to the inputted color
