### ISSUE TITLE
Setting X Axis min to 5 hangs forever

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulse#125]
![image](https://user-images.githubusercontent.com/7853605/109698571-89dbf200-7b5d-11eb-89fb-fcf1203d62a2.png)

**Comment by markhalonen** [comment]
dunno if it's because min is greater than max. but would be very annoying if you were in middle of analysis and entered wrong number

**Comment by jotaivalkoski** [comment]
i cant replicate this.

**Comment by jotaivalkoski** [comment]
![Screenshot from 2021-03-02 13-53-18](https://user-images.githubusercontent.com/25654450/109699612-c5c38700-7b5e-11eb-8e9c-a77d5f0bdac9.png)

**Comment by jotaivalkoski** [comment]
should present dialog.

**Comment by markhalonen** [comment]
[REL-2000-2.samcomp.zip](https://github.com/relinc/SurePulse/files/6071118/REL-2000-2.samcomp.zip)

sorry here's the file I produced it on

**Comment by jotaivalkoski** [comment]
@markhalonen I think we can close this one, right?
