### ISSUE TITLE
Chart Label Edits

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulse#127]
From Luke

> Chart Label Modifiers
All titles say the same thing
The new edit menu is much better for axis and title changes all at once.   Can the current values be populated so the user doesn’t have to retype everything whenever a change is needed?

**Comment by jotaivalkoski** [comment]
you only need to enter the fields you want to change

**Comment by markhalonen** [comment]
Yes, he's saying if current value is "Stress Vs Strain", it should fill that value into the Text Field, so he doesn't have to re-type everyting
