### ISSUE TITLE
Create file format in JSON

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulse#16]
Save all new samples in JSON, ask which type a sample is before loading.

**Comment by markhalonen** [comment]
One thing I randomly remembered about this... I didn't really like how the JSON libraries mapped java classes directly to JSON. This means that someone innocently changing a variable name would make that class incompatible with the existing JSON files on disk... something to keep in mind.

**Comment by bhalonen** [comment]
We aren't using variable names, using the old keys you used. Seemed easiest/simple to compare file versions.
