### ISSUE TITLE
Reduced data not working on export from excel

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulse#4]
Data reduction has been a feature in excel to make the file sizes more manageable. 

It isn't working.

I think the bug arises on the line that is linked below.

https://github.com/relinc/SurePulse/blob/0fe461999caaf6b71bff7d270440d3d94abc11ec/Viewer/src/net/relinc/viewer/GUI/ExportGUI.java#L538

**Comment by bhalonen** [comment]
The test uses something besides null.

**Comment by bhalonen** [comment]
https://github.com/relinc/SurePulse/blob/0fe461999caaf6b71bff7d270440d3d94abc11ec/Libraries/src/net/relinc/libraries/data/ModifierFolder/Reducer.java#L50

Looking like it is not functional, nor is it a quick fix.

**Comment by markhalonen** [comment]
The algorithm for reducing the data could probably use some scrutiny.. should it interpolate? Are there libraries for this?

**Comment by markhalonen** [comment]
https://github.com/relinc/SurePulse/blob/0fe461999caaf6b71bff7d270440d3d94abc11ec/Libraries/src/net/relinc/libraries/data/ModifierFolder/Reducer.java#L78

**Comment by markhalonen** [comment]
We need to be able to specify sampling with either a frequency or "points to keep".

This way users can ensure their timesteps remain the same across their testing.
