### ISSUE TITLE
Export face forces to excel 

### ISSUE THREAD

**Issue by bhalonen** [relinc/SurePulse#40]
Many results can be exported in excel, face force is not one of them. This export happens in the analysis page.

**Comment by bhalonen** [comment]
https://github.com/relinc/SurePulse/blob/c2020878b3e04b62cfe81e3ff8afa01e90308fd2/Viewer/src/net/relinc/viewer/GUI/ExportGUI.java#L442

**Comment by markhalonen** [comment]
This will require changing `ExcelMakerConsole.exe`, which is a C# library that turns the job file into Excel using the EPPlus library. 

https://github.com/relinc/ExcelMakerConsole

You'll pry need Windows / Visual Studio for this task.
