### ISSUE TITLE
Switching units in Bar Setup Broken

### ISSUE THREAD

**Issue by markhalonen** [relinc/SurePulse#64]
Switching from English to Metric and back to English has unexpected behavior.

**Comment by bhalonen** [comment]
![23C57936-6855-47A4-B05E-C5AC6F4F21A8-3472-0000014A73F04A97](https://user-images.githubusercontent.com/7853544/88204636-9092a600-cc19-11ea-8a84-a191485200df.jpg)
]
issue exists elsewhere.
